// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpwienIHbaGhCcrF_9HVnSZTf2uPkEh0',
    appId: '1:1082812033662:web:54929e1c5211557dcec62f',
    messagingSenderId: '1082812033662',
    projectId: 'himo-chat-e0450',
    authDomain: 'himo-chat-e0450.firebaseapp.com',
    storageBucket: 'himo-chat-e0450.appspot.com',
    measurementId: 'G-PVR01KW50L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLLOMQMAjjj1DHOGoV3wmLrDnFPSsLK08',
    appId: '1:1082812033662:android:b4950ca951238c90cec62f',
    messagingSenderId: '1082812033662',
    projectId: 'himo-chat-e0450',
    storageBucket: 'himo-chat-e0450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDTo6r65fxS4apFC1XSA_9vC41oQaurk',
    appId: '1:1082812033662:ios:194d27a60beda6f7cec62f',
    messagingSenderId: '1082812033662',
    projectId: 'himo-chat-e0450',
    storageBucket: 'himo-chat-e0450.appspot.com',
    iosClientId: '1082812033662-gd788migr0jaaqf84950r5ud168l4rjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.himochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLDTo6r65fxS4apFC1XSA_9vC41oQaurk',
    appId: '1:1082812033662:ios:5d3f3c1be3653770cec62f',
    messagingSenderId: '1082812033662',
    projectId: 'himo-chat-e0450',
    storageBucket: 'himo-chat-e0450.appspot.com',
    iosClientId: '1082812033662-7g0neg8uqaafl9ocrkr4hajmqv66urha.apps.googleusercontent.com',
    iosBundleId: 'com.example.himochat.RunnerTests',
  );
}
